### ISSUE TITLE
REST call "status"

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-Apriori-R#18]
This request should check the state of EasyMiner-Apriori-R and the appropriate dependencies. 

responses:
```json
{"status":"ok"}
```

```json
{"status":"error", "message":"Error description..."}
```

**Comment by propi** [comment]
Fixed in the bitbucket version. Url for the status service is: /api/v1/status
It returns 200 if all dependent services are available or 503 if some dependency is not available. The Miner service has these dependencies: RServe, MySQL, User service
