### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-Apriori-R#4]
The service should accept connection addressed not only with IPv4, but also with IPv6.

**Comment by propi** [comment]
There are 4 environment variables which should be defined before running the rest app:

R_SERVER - address to a RServe
R_JDBC - path to a mysql jdbc directory within R server
REST_ADDRESS - rest address (you can define ip4, ip6 or domain), domain name is prefered
REST_PORT - rest port
