### ISSUE TITLE
Support for utf-8 accented characters in values

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-Apriori-R#9]
In the data values, the application has to support diacritics in values of data columns. 

Currently, it returns error:
```xml
<error>
      <code>500</code>
      <name>org.rosuda.REngine.REngineException</name>
      <message>eval failed, request status: error code: 127</message>
</error>

**Comment by propi** [comment]
I fixed some classes and added unit tests for mining with unusual inputs; all tests were performed successfully.

Now there shouldn't be any problem with "attribute names" or "values" with spaces and UTF-8 chars

**Comment by propi** [comment]
Don't forget to post your PMML input with content type header: application/xml;charset=utf-8. It uses ISO-8859-1 as the default encoding without a specified charset.

**Comment by propi** [comment]
Now every quotation mark is filtered

**Comment by propi** [comment]
There are other problems with special characters in the R script. The arules package returns association rules in this format:

1           {attr=value,attr=value} => {attr=value} 0.01019253  1.0000000 1.7041632

If attr or value contains comma or equating it might be problem with the result parsing!

**Comment by propi** [comment]
If there is some quotation mark within a value or an attribute name it should throw exception instead of filtering these characters!

**Comment by propi** [comment]
quotation marks " and ' are invalid input characters. Program will throw an exception if one of these characters occurs in input.

**Comment by propi** [comment]
Now, program checks whether all returned R arules are valid. It compares the arule name and value to the database colname and value. If any name or value doesn't occur in database, it will throw an exception.
